ZNU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from ZNU.settings import MEDIA_URL, MEDIA_ROOT, DEBUG


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls', namespace="main_page")),
    path('users/', include('users.urls', namespace="users")),
    path('zayavki/', include('zayavki.urls', namespace="zayavki")),
    # path('comments/', include('comments.urls', namespace="comments")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

zayavki/urls.py
from django.urls import path
from zayavki.views import ZayavkaUpdate, ZayavkaDetail, ZayavkaCreate, ZayavkaFilterList, process_command, add_comment, return_to_prev_page



app_name = "zayavki"

urlpatterns = [
    path("", ZayavkaFilterList.as_view(), name="zayavki_list"),
    path('<str:filter>/', ZayavkaFilterList.as_view(), name='zayavki_filter_list'),    
    path("create", ZayavkaCreate.as_view(), name="zayavka-create"),
    path("<int:pk>", ZayavkaDetail.as_view(), name="zayavka-detail"),
    path("<int:pk>/update", ZayavkaUpdate.as_view(), name="zayavka-update"),
    path("command", process_command, name="zayavka-command"),
    path("add_comment", add_comment, name="add-comment"),
    path("return_to_prev_page", return_to_prev_page, name="return_to_prev_page")
    
    
    
]

zayavki/models.py
from enum import Enum, auto
from django.db import models
from django.db.models import manager
from django.db.models.query import QuerySet
from users.models import Roles, User, Category, Shops
from django.urls import reverse


# Create your models here.

class FiltersOfZayavok(models.Model):
    label = models.CharField(max_length=30)  # Название/отображение на сайте
    link = models.CharField(max_length=10)  # как будет отображаться в ссылке
    status1 = models.BooleanField(default=None, null=True)  # одобрено
    status2 = models.BooleanField(default=None, null=True)  # отклонено
    status3 = models.BooleanField(default=None, null=True)  # уценено
    status4 = models.BooleanField(default=None, null=True)  # ценник сменен
    status5 = models.BooleanField(default=None, null=True)  # в архиве
    # остальные поля - резервные
    status6 = models.BooleanField(default=None, null=True)
    # для каких ролей пользователя является дефолтным
    for_roles = models.ManyToManyField(Roles)

    class Meta:
        verbose_name_plural = "Фильтры заявок"
        verbose_name = "Фильтр заявок"

    def __str__(self):
        return self.label


class Zayavka(models.Model):
    user = models.ForeignKey(
        User, default=None, null=True, on_delete=models.PROTECT)
    # shop = models.ForeignKey(Shops, default=None, null=True, on_delete=models.PROTECT)
    data = models.DateField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    description = models.TextField()
    clarification = models.TextField()
    foto1 = models.ImageField(upload_to="zayavki/foto", blank=True)
    foto2 = models.ImageField(upload_to="zayavki/foto", blank=True)
    status1 = models.BooleanField(default=False)  # одобрено
    status2 = models.BooleanField(default=False)  # отклонено
    status3 = models.BooleanField(default=False)  # уценено
    status4 = models.BooleanField(default=False)  # ценник сменен
    status5 = models.BooleanField(default=False)  # в архиве
    # остальные поля - резервные
    status6 = models.BooleanField(default=False)
    clarification_of_manager = models.CharField(max_length=150, blank=True)
    manager = models.ForeignKey(
        User, default=None, null=True, on_delete=models.PROTECT, related_name='+')
    # manager - тот, кто последний вносил изменения в статусы

    class Meta:
        verbose_name_plural = "Заявки"
        verbose_name = "Заявка"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/zayavki/{self.id}'
        # TODO вернуть на страницу заявки detail
        # def get_absolute_url(self):
        #     return reverse('author-detail', kwargs={'pk': self.pk})

    def get_count_comments(self):
        return Comments2.objects.filter(object_id=self.id).count()


class Comments2(models.Model):
    # id объекта, к которому будут относиться комментарии, например, Заявки
    object_id = models.PositiveSmallIntegerField(null=True)
    # дата и время создания комментария
    created = models.DateTimeField(auto_now_add=True)
    # id пользователя, который является автором комментария
    autor = models.CharField(max_length=50, default="")
    body = models.TextField(null=True)  # текст комментария
    # для отключения неприемлемых комментариев
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Комментарии"
        verbose_name = "Комментарий"

    def __str__(self) -> str:
        return self.body


class EventNotification(Enum):
    CREATE_ZAYAVKA = 'Магазин "#" создал новую заявку на уценку'
    ADD_COMMENT = 'Добавлен новый комментарий в заявку'
    SET_STATUS1_TRUE = 'Менеджер одобрил заявку'
    SET_STATUS2_TRUE = 'Менеджер отклонил заявку'
    SET_STATUS3_TRUE = 'Менеджер перевел товар в качество БУ или Discount'
    SET_STATUS4_TRUE = "4"
    SET_STATUS5_TRUE = "5"


class Notifications2(models.Model):
    created = models.DateField(auto_now_add=True)
    recipient = models.ManyToManyField(User)
    zayavka = models.ForeignKey(
        Zayavka, default=None, null=True, on_delete=models.PROTECT)
    text = models.CharField(max_length=250)

    class Meta:
        verbose_name_plural = "Уведомления"
        verbose_name = "Уведомление"

    def __str__(self):
        return self.text

zayavki/forms.py
from typing import Dict
from django import forms

from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.shortcuts import resolve_url
from zayavki.models import Zayavka, Category
from users.models import User
from .models import Comments2

# def get_gategories(qset:QuerySet):
#         all = qset.objects.all()
#         result = []
#         for i, category in enumerate(all):
#             result.append((str(i), category))
#         return result    




class AddZayavkaForm(forms.ModelForm):
    # id_user=0
    # def __init__(self, id_user, instance):
    #     super().__init__(self, instance)
    #     id_user = id_user

    name_class = "form-control form-control-sm fw-bold"
    attrs_for_code = {"class" : name_class,
                    'placeholder' : "Введите код товара",}
    attrs_for_name = {"class" : name_class,
                    'placeholder' : "Введите номенклатуру"}
    attrs_for_category = {"class" : name_class,
                    'placeholder' : "Выберите категорию"}
    attrs_for_description = {"class" : name_class, "style" : "height: 70px",
                    'placeholder' : "Введите описание товарного вида"}
    attrs_for_clarification = {"class" : name_class, "style" : "height: 70px",
                    'placeholder' : "Поясните причины и обстоятельства"}
    attrs_for_foto1 = {"class" : "form-control form-control-sm fw-bold",'placeholder' : "Добавьте фото №1"}                
    attrs_for_foto2 = {"class" : "form-control form-control-sm fw-bold",'placeholder' : "Добавьте фото №2"}
    
    
    code = forms.CharField(label="Код номенклатуры:", widget=forms.TextInput(attrs=attrs_for_code))
    name = forms.CharField(label="Наименование номенклатуры:",widget=forms.TextInput(attrs=attrs_for_name))
    category = forms.ModelChoiceField (Category.objects, label="Категория:",widget=forms.Select(attrs={"class":name_class}))
    description = forms.CharField(label="Описание товарного вида:",widget=forms.Textarea(attrs=attrs_for_description))
    clarification = forms.CharField(label="Пояснения:",widget=forms.Textarea(attrs=attrs_for_clarification))
    foto1 = forms.FileField(label="Приложите фото №1: ",widget=forms.FileInput(attrs=attrs_for_foto1), required=False)
    foto2 = forms.FileField(label="Приложите фото №2: ",widget=forms.FileInput(attrs=attrs_for_foto2), required=False)
    
    class Meta:
        model = Zayavka
        fields = ("code", "name", "category","description", "clarification", "foto1", "foto2")    

    # def set_user(self, new_user):
    #     data = self.data.copy()
    #     data['user'] = new_user
    #     self.data = data
           
        


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comments2
        fields = ('body',)
    
    name_class = "form-control form-control-sm fw-bold"    
    attrs_for_body = {"class" : name_class, "style" : "height: 70px",
                    'placeholder' : "Введите комментарий"}   
    body = forms.CharField(widget=forms.Textarea(attrs=attrs_for_body))     

zayavki/views.py
from .forms import CommentForm
from .models import Comments2, EventNotification
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView
# from .utils import get_data_from_model_Zayavka, get_filters_for_template
from .models import Notifications2

from users.models import User

from zayavki.forms import AddZayavkaForm
from zayavki.models import Zayavka
from .services_zayavka_list import get_users_queryset_onfilter, get_users_default_filter, get_listdict_of_filters_with_counts
from .services_zayavka_detail import ZayavkaProperties
from .services_comments import get_comments
from .service_notifications import MakerNotification, get_notifications


KOL_RECORDS_ON_PAGE = 10


def return_to_prev_page(request):
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

class ZayavkaFilterList(LoginRequiredMixin, ListView):
    '''Представление списка заявок'''
    model = Zayavka
    paginate_by = KOL_RECORDS_ON_PAGE
    template_name = "zayavki/zayavka_list.html"
    context_object_name = "zayavki"

    def get_queryset(self):
        """Возвращает пользовательский набор заявок на основании текущего фильтра и текущего пользователя"""
        return get_users_queryset_onfilter(self.request.user, self.get_filter_from_post_or_default())

    def get_filter_from_post_or_default(self):
        """Возвращает параметр "filter" из полученного POST
        Если в POST нет параметра filter, возвращает фильтр текущего пользователя по умолчанию"""
        return self.kwargs.get('filter', get_users_default_filter(self.request.user))

    def get_context_data(self, **kwargs):
        # заполняем контекст для передачи в шаблон
        context = super().get_context_data(**kwargs)
        context["title"] = "Заявки на уценку"
        context["name_page"] = "Заявки на уценку"
        context['filters'] = get_listdict_of_filters_with_counts(self.request.user)
        context['cur_filter'] = self.get_filter_from_post_or_default()
        context['notifications'] = get_notifications(self.request.user)
        return context


class ZayavkaCreate(LoginRequiredMixin, CreateView):

    model = Zayavka
    template_name = "zayavki/zayavka_create.html"
    form_class = AddZayavkaForm

    def form_valid(self, form):
        # Добавить текущего пользователя, кто создал заявку
        form.instance.user = self.request.user
        zayavka = form.save(commit=False)
        zayavka.manager = User.objects.filter(
            role__namerole__startswith="Менеджер - ").get(role__work_category=zayavka.category)
        zayavka.save()
        # Создать уведомление
        MakerNotification(self.request.user, zayavka, EventNotification.CREATE_ZAYAVKA).create_notification()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        # Добавить данные в контекст, передаваемый в шаблон
        context = super().get_context_data(**kwargs)
        context["title"] = "Новая заявка"
        context["name_page"] = "Новая заявка"
        context['prev'] = self.request.GET.get('prev')
        return context

    def get_success_url(self):
        # Перенаправить после успешного создания заявки. TODO заменить на reverse_lazy, переадресацию на созданную заявку detail
        # return reverse('zayavki:zayavki_list')
        return self.request.GET.get('prev', reverse('zayavki:zayavki_list'))

    
        

def process_command(request):
    """ Обработка нажатий кнопок в заявке"""
    if request.method=="POST":
        _id = request.POST['_id']
        zayavka = Zayavka.objects.get(id=_id)
        if '_edit' in request.POST:
            return HttpResponseRedirect(reverse('zayavki:zayavka-update', args=(_id,)))
        if '_status1' in request.POST:
            zayavka.status1 = True
            zayavka.status2 = False
            zayavka.manager = request.user
            MakerNotification(request.user, zayavka, EventNotification.SET_STATUS1_TRUE).create_notification()    
        if '_status2' in request.POST:        
            zayavka.status1 = False
            zayavka.status2 = True
            zayavka.manager = request.user
            MakerNotification(request.user, zayavka, EventNotification.SET_STATUS2_TRUE).create_notification()                  
        if '_cancel_approve' in request.POST:        
            zayavka.status1 = False
            zayavka.status2 = False
        if '_status3' in request.POST:
            zayavka.status3 = not zayavka.status3
            zayavka.manager = request.user
            MakerNotification(request.user, zayavka, EventNotification.SET_STATUS3_TRUE).create_notification()
        if '_status4' in request.POST:
            zayavka.status4 = not zayavka.status4
            zayavka.manager = request.user
        if '_status5' in request.POST:
            zayavka.status5 = not zayavka.status5
            zayavka.manager = request.user
        zayavka.save()
        return HttpResponseRedirect(reverse('zayavki:zayavka-detail', args=(_id,)))

class ZayavkaDetail(LoginRequiredMixin, DetailView):
    model = Zayavka
    template_name = "zayavki/zayavka_detail.html"
     
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        zayavka = ZayavkaProperties(self.get_object(), self.request.user) 
        context["title"] = "Просмотр заявки"
        context["name_page"] = "Просмотр заявки"
        context["access_open"] = zayavka.is_access_open()         
        context["status_as_text"] = zayavka.get_status_as_text()               
        context['btns'] = zayavka.get_btns() 
        context['comments'] = get_comments(self.get_object())
        context['comments_form'] = CommentForm 
        context['prev'] = self.request.GET.get('prev') 
        return context
    
       

class ZayavkaUpdate(LoginRequiredMixin, UpdateView):
    model = Zayavka
    template_name = "zayavki/zayavka_create.html"
    form_class = AddZayavkaForm

    def form_valid(self, form):
        # Добавить текущего пользователя, кто создал заявку
        form.instance.user = self.request.user
        zayavka = form.save(commit=False)
        zayavka.manager = User.objects.filter(
            role__namerole__startswith="Менеджер - ").get(role__work_category=zayavka.category)
        zayavka.save()
        # Создать уведомление
        MakerNotification(self.request.user, zayavka, EventNotification.CREATE_ZAYAVKA).create_notification()
        return super().form_valid(form)


    
    
        
    
    
    
def add_comment(request):
    """ Обработка добавления комментария """       
    if request.method=="POST":
        _id = int(request.POST['_id'])    
        zayavka = Zayavka.objects.get(id=_id)      
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.autor = request.user
            comment.object_id = _id  
            comment.save()    
            MakerNotification(request.user, zayavka, EventNotification.ADD_COMMENT).create_notification()        
            return HttpResponseRedirect(reverse('zayavki:zayavka-detail', args=(_id,)))
        else:
            print ("Что-то пошло не так.")
            print (form.data)
    else:
        return HttpResponseRedirect(reverse('zayavki:zayavki_list'))      

zayavki/templates/zayavki/add_zayavka.html
{% extends 'main_page/base.html' %}
{% load  static %}

{% block name_app %}
    <a class="navbar-brand flex-grow-1" href="{% url 'zayavki:page_view' %}"> > Заявки на уценку > {{ name_page }} </a>
{% endblock name_app %}


{% block content %}

<div class="row mt-1">
     <form action="" method="post" enctype="multipart/form-data">
     {% csrf_token %} 
     
     <div class="col-md-3 col-sm-12">
        <label class="form-label mb-0" for={{form.code.id_for_input}}>Код товара:</label>
        {{form.code}}
     </div>
     <div class="col-md-6 col-sm-12">
        <label class="form-label mb-0 mt-1 " for={{form.name.id_for_input}}>Наименование товара:</label>
        {{form.name}}
     </div>  
    <div class="col-md-3 col-sm-12">
        <label class="form-label mb-0 mt-1" for={{form.category.id_for_input}}>Категория товара:</label>
        {{form.category}}
    </div>  
    <div class="col-md-6 col-sm-12">
        <label class="form-label mb-0 mt-1" for={{form.description.id_for_input}}>Описание товарного вида:</label>
        {{form.description}}
        {% if form.instance.foto1 %}
            <a href="/media/{{form.instance.foto1}}"  target="_blank" class="text-decoration-none">                
                <i class="fa fa-file-image-o fa-lg" aria-hidden="true"></i>
            </a>
        {% endif %}
        {% if form.instance.foto2 %}
            <a href="/media/{{form.instance.foto2}}"  target="_blank" class="text-decoration-none">
                <i class="fa fa-file-image-o fa-lg" aria-hidden="true"></i>
            </a>
        {% endif %}
    </div>  
    <div class="col-md-6 col-sm-12">
        <label class="form-label mb-0 mt-1" for={{form.clarification.id_for_input}}>Причины и обстоятельства утраты товарного вида:</label>
        {{form.clarification}}
    </div> 
    <div class="col-md-6 col-sm-12">
        <label class="form-label mb-0 mt-1" for={{form.foto1.id_for_input}}>Фото 1:</label>
        {{form.foto1}}
    </div> 
    <div class="col-md-6 col-sm-12">
        <label class="form-label mb-0 mt-1" for={{form.foto1.id_for_input}}>Фото 2:</label>
        {{form.foto1}}
    </div> 
    <input class="col-md-3 col-sm-12 btn btn-info btn-block mt-2 " type="submit" value="Сохранить">    
    <a href="" class="col-md-3 col-sm-12 btn btn-info btn-block mt-2 ">Отменить</a>   
    </form>

</div>
               
{% endblock content %}

zayavki/templates/zayavki/comments.html
<h4 class="mt-3">Комментарии:</h4>
{% for comment in comments%}
    <div class="card" style="width: 100;">
    {% comment %} <img src="..." class="card-img-top" alt="..."> {% endcomment %}
    <div class="card-body">
        <h5 class="card-title"> {{ comment.autor }}</h5>
        <p class="card-text">{{ comment.body}}</p>
    </div>
    </div>
{% endfor %}  


<br>
<br>
Добавить комментарий:
<form action="{% url 'zayavki:add-comment' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="_id" value="{{zayavka.id}}">
    <div class="col-md-6 col-sm-12">
        <label class="form-label mb-0 mt-1 " for={{comments_form.body.id_for_input}}>Текст комментария:</label>
        {{ comments_form.body}}
     </div>  
    <input class="col-md-3 col-sm-12 btn btn-info btn-block mt-2 " type="submit" value="Отправить" >
</form>        

zayavki/templates/zayavki/notifications.html
<h4>Уведомления</h4>

{% for notification in notifications %}
    {% comment %} <p> {{notification.created}} : {{ notification.text }} <a href="{% url 'zayavki:zayavka-detail' notification.zayavka_id %}"> Открыть</a> {% endcomment %}
    <div class="list-group">
        <a href="{% url 'zayavki:zayavka-detail' notification.zayavka_id %}" 
           class="list-group-item list-group-item-action mb-1" aria-current="true">
            <div class="d-flex w-100">            
                <small class="pe-2 m-0">{{notification.created|date:"d E"}}:</small>
                <small class="p-0 m-0">{{ notification.text }}</small>
            </div>           
        </a>
    </div>    


{% endfor %}

    

zayavki/templates/zayavki/zayavka_detail.html
{% extends 'main_page/base.html' %}
{% load  static %}

{% block name_app %}
    <a class="navbar-brand flex-grow-1" href="{% url 'zayavki:zayavki_list' %}"> > Заявки на уценку > {{ name_page }} </a>
{% endblock name_app %}


{% block content %}
    <a href="{{ prev }}" class="btn btn-link mb-2">Вернуться к списку</a>
    {% comment %} TODO сделать редирект на предыдущую страницу {% endcomment %}

    {% if access_open %}  
        <h2>Просмотр заявки</h2>
        <p> Дата: {{ zayavka.data }} </p>
        <p> Магазин: {{ zayavka.user.shop }} </p>
        <p> Код товара:  {{ zayavka.code }}</p>
        <p> Наименование:  {{ zayavka.name }}</p>
        <p> Категория:  {{ zayavka.category }}</p>
        <p> Описание товарного вида: {{ zayavka.description }}</p>
        <p> Фото: 
            {% if zayavka.foto1 %}
                <a href="/media/{{zayavka.foto1}}"  target="_blank" class="text-decoration-none">
                    <i class="fa fa-file-image-o fa-lg" aria-hidden="true"></i>
                </a>
            {% endif %}
            {% if zayavka.foto2 %}
                <a href="/media/{{zayavka.foto2}}"  target="_blank" class="text-decoration-none">
                    <i class="fa fa-file-image-o fa-lg" aria-hidden="true"></i>
                </a>
            {% endif %}  </p>             
        <p> Пояснения: {{ zayavka.clarification }}</p>
        <p> Статус: {{ status_as_text }}</p>
        
        <form action="{% url 'zayavki:zayavka-command' %}" method="post">
            {% csrf_token %}
            {% comment %} в скрытое поле _id записывается текущий id {% endcomment %}
            <input type="hidden" name="_id" value="{{zayavka.id}}">
            {% for btn in btns  %} 
                {% comment %} в имя поля записывается команда {% endcomment %}
                <input  type="submit" class="btn {{btn.btn_class}} mt-2" value="{{btn.btn_value}}" name="{{btn.btn_name}}">           
            {% endfor %}
        </form> 

        {% include "zayavki/comments.html" %}

    {% else %}
        <p> Данная заявка вам недоступна! </p>    
    {% endif %}              
{% endblock content %}

zayavki/templates/zayavki/zayavka_list.html
{% extends 'main_page/base.html' %}
{% load  static %}

{% block css %}
    <link href= {% static 'styles.css' %} rel="stylesheet">
{% endblock css %}


{% block name_app %}
    <a class="navbar-brand flex-grow-1" href="{% url 'zayavki:zayavki_list' %}"> > Заявки на уценку</a>
{% endblock name_app %}



{% block content %}
    <div >         
        {% comment %} Кнопка СОЗДАТЬ НОВУЮ ЗАЯВКУ {% endcomment %}
        <div class="row justify-content-between">
            <div class="col-8 m-auto">
                <h2>Список заявок</h2>
            </div>
            <div class="col-4">
                <div class="col my-2 text-end">
                    <a class="btn btn-success text-nowrap" href="{% url 'zayavki:zayavka-create' %}?prev={{ request.path }}">Создать новую заявку</a> 
                </div>  
            </div>
        </div>
              
        {% comment %} БЛОК ФИЛЬТРОВ {% endcomment %}
        <div class="select_filter">
            {% for one_filter in filters %}
                <div>
                    <a 
                      {% if one_filter.link != cur_filter %} class="btn btn-outline-primary btn-sm text-nowrap" {% else %} class="btn btn-primary btn-sm text-nowrap" {% endif %} 
                      href="{% url 'zayavki:zayavki_filter_list' one_filter.link %}" 
                      role="button">
                      {{ one_filter.label }} {{ one_filter.count }}                      
                    </a>                    
                </div>    
            {% endfor %}            
        </div>
        
        {% comment %} ТАБЛИЦА ЗАЯВОК {% endcomment %}
        <div class="table-responsive">
        <table class="table table-hover table-bordered table-sm my_table  ">
            <thead>
                <tr class="">                
                    <th class="col-1">Дата</th>
                    <th class="col-1">Номер заявки</th>
                    <th class="col-1">Магазин</th>
                    <th class="col-1">Код товара</th>
                    <th class="col-2" >Номенклатура</th>
                    <th class="col-3">Товарный вид</th>
                    <th class="col-3">Пояснения</th>
                    <th class="col">Решение</th>
                    <th class="col">Уценка в 1С</th>
                    <th class="col">Уценка на витрине</th>
                </tr>
            </thead>              
            <tbody>    
            {%for zayavka in zayavki%}
                <tr>                   
                    <td>{{zayavka.data|date:"d.m.Y"}}</td>
                    <td>{{zayavka.id}}</td>
                    <td>{{zayavka.user.shop}}</td>
                    <td>{{zayavka.code}}</td>
                    <td>
                        <a href="{% url 'zayavki:zayavka-detail' zayavka.id %}?prev={{ request.path }}"> {{zayavka}} </a>
                    </td>
                    <td>{{zayavka.description}}
                        {# иконка наличия фотографий в заявке #}
                        {% if zayavka.foto1 %}
                            <a href="/media/{{zayavka.foto1}}"  target="_blank" class="text-decoration-none">
                                <i class="fa fa-file-image-o fa-lg" aria-hidden="true"></i>
                            </a>
                        {% endif %}
                        {% if zayavka.foto2 %}
                            <a href="/media/{{zayavka.foto2}}"  target="_blank" class="text-decoration-none">
                                <i class="fa fa-file-image-o fa-lg" aria-hidden="true"></i>
                            </a>
                        {% endif %}                    
                    </td>
                    <td>{{zayavka.clarification}} 
                        {# иконка количества комментариев в заявке #}
                        {% if zayavka.get_count_comments > 0 %}
                        <a href="{% url 'zayavki:zayavka-detail' zayavka.id %}?prev={{ request.path }}" class="text-decoration-none">
                           <i class="fa fa-comment-o" aria-hidden="true"></i> {{ zayavka.get_count_comments }}
                        </a> 
                        {% endif %}                       
                    </td>
                    <td>{% if zayavka.status1 %}
                            <i class="fa fa-check" style="color:green" aria-hidden="true"></i>
                        {% elif zayavka.status2 %}
                            <i class="fa fa-times" style="color:red" aria-hidden="true"></i>
                        {% else %}
                            <i class="fa fa-hourglass-half" style="color:gray" aria-hidden="true"></i>
                        {% endif %}    
                    </td>
                    <td>{% if zayavka.status1 and zayavka.status3 %}
                            <i class="fa fa-check"  style="color:green" aria-hidden="true"></i>
                        {% elif  zayavka.status1 and not zayavka.status3%}
                            <i class="fa fa-hourglass-half"  style="color:gray" aria-hidden="true"></i>
                        {% endif %} 
                            
                    </td>
                    <td>{% if zayavka.status3 and zayavka.status4 %}
                            <i class="fa fa-check" style="color:green" aria-hidden="true"></i>
                        {% elif zayavka.status3 and not zayavka.status4%}
                            <i class="fa fa-hourglass-half" style="color:gray" aria-hidden="true"></i>
                        {% endif %} 
                    </td>
                </tr>
            {%endfor%}
        </tbody>    
        </table>
        </div>
       
        {% if paginator.num_pages > 1 %}
        <nav aria-label="Page navigation" class="mt-2">
            <ul class="pagination justify-content-center">
                <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                <a class="page-link" 
                    href="{% if page_obj.has_previous %} {% url 'zayavki:zayavki_filter_list' cur_filter %}?page={{page_obj.previous_page_number}} {% else %}#{% endif %}" 
                    tabindex="-1">Предыдущая</a>
                </li>
                
                {% for p in paginator.page_range %}                    
                    <li class="page-item {% if page_obj.number == p %} active{% endif %}">
                        <a class="page-link" 
                            href="{% url 'zayavki:zayavki_filter_list' cur_filter %}?page={{p}}">
                            {{p}}
                        </a>
                    </li>
                {% endfor %}
                
                <li class="page-item {% if not page_obj.has_next %} disabled  {% endif %}">
                <a class="page-link" 
                    href="{% if page_obj.has_next %} {% url 'zayavki:zayavki_filter_list' cur_filter%}?page={{page_obj.next_page_number}} {% else %}#{% endif %}">
                    Следующая
                </a>
                </li>
            </ul>
        </nav>
        {% endif %}

        {# Блок уведомлений #}
        {% include "zayavki/notifications.html" %}
       
    </div>
{% endblock content %}