ZNU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from ZNU.settings import MEDIA_URL, MEDIA_ROOT, DEBUG


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls', namespace="main_page")),
    path('users/', include('users.urls', namespace="users")),
    path('zayavki/', include('zayavki.urls', namespace="zayavki")),
    # path('comments/', include('comments.urls', namespace="comments")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main_page/urls.py
from django.urls import path
from .views import index

app_name = "main_page"
urlpatterns = [
    path("", index, name="index")]

users/urls.py
from django.urls import path
from .views import login, profile, register, logout

app_name = "users"
urlpatterns = [
    path("login", login, name="login"),
    path("profile", profile, name="profile"),
    path("register", register, name="register"),
    path("logout", logout, name="logout")
]

zayavki/urls.py
from django.urls import path
from zayavki.views import ZayavkaUpdate, ZayavkaDetail, ZayavkaCreate, ZayavkaFilterList, process_command, add_comment, return_to_prev_page



app_name = "zayavki"

urlpatterns = [
    path("", ZayavkaFilterList.as_view(), name="zayavki_list"),
    path('<str:filter>/', ZayavkaFilterList.as_view(), name='zayavki_filter_list'),    
    path("create", ZayavkaCreate.as_view(), name="zayavka-create"),
    path("<int:pk>", ZayavkaDetail.as_view(), name="zayavka-detail"),
    path("<int:pk>/update", ZayavkaUpdate.as_view(), name="zayavka-update"),
    path("command", process_command, name="zayavka-command"),
    path("add_comment", add_comment, name="add-comment"),
    path("return_to_prev_page", return_to_prev_page, name="return_to_prev_page")
    
    
    
]

main_page/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    template = "main_page/index.html"
    context = {
        "title": "Главная страница"        
    }
    return render(request, template, context)

main_page/templates/main_page/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title> {{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href= {% static 'bootstrap-5/css/bootstrap.min.css' %}  rel="stylesheet">
    <!-- Custom styles for this template -->
    {% block css %}{% endblock css %}

</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand " 
           href="{% url 'main_page:index' %}">
           Gamepark Office
        </a>
        {% block name_app %}{% endblock name_app %}
        
        <button class="navbar-toggler me-auto" 
                type="button"
                data-bs-toggle="collapse" 
                data-bs-target="#navbarContent" 
                aria-controls="navbarContent" 
                aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse flex-grow-0" id="navbarContent">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:profile' %}">{{user.username }} <i class="fas fa-user-circle"></i></a>
                </li>
                    {% if user.shop %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:profile' %}">{{user.shop }} <i class="fa fa-map-marker" aria-hidden="true"></i></a>
                        </li>
                    {% endif %}    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>    
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>           
        </div>
        
    </div>   
</nav>

<div class="container">
    {% block content %} {% endblock content %}
</div>






<!-- Bootstrap core JavaScript -->
<script src={% static 'bootstrap-5/js/bootstrap.bundle.min.js' %} ></script>
<!-- FontAwesome script -->
<script src={% static 'fontawesome/fontawesome-icons.js' %} crossorigin="anonymous"></script>
</body>
</html>

main_page/templates/main_page/index.html
{% extends 'main_page/base.html' %}
{% load  static %}

{% block css %}
    
{% endblock css %}
    


{% block content %}

<div class="card-deck d-flex justify-content-center mt-3">
  <div class="row text-center justify-content-center">
  <div class="card col-sm-12 col-md-6 col-lg-3 me-2 mb-2">
    <img class="card-img-top img-fluid rounded mt-2" src="{% static 'title01.jpg' %}" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Заявки на уценку</h5>
     </div>
    <div class="card-footer bg-white border-0">
        <a href="{% url 'zayavki:zayavki_list' %}" class="btn btn-primary ">Перейти</a>
    </div>
  </div>
  <div class="card col-sm-12 col-md-6 col-lg-3 me-2 mb-2">
    <img class="card-img-top img-fluid rounded mt-2" src="{% static 'title02.jpg' %}" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Аттестации продавцов</h5>     
    </div>
    <div class="card-footer bg-white border-0">
        <a href="#" class="btn btn-primary disabled">Недоступно</a>
    </div>
  </div>
  <div class="card col-sm-12 col-md-6 col-lg-3 me-2 mb-2">
    <img class="card-img-top img-fluid rounded mt-2" src="{% static 'title02.jpg' %}" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Разработка</h5>     
    </div>
    <div class="card-footer bg-white border-0">
        <a href="#" class="btn btn-primary disabled">Недоступно</a>
    </div>
    </div>
  </div>
</div>

{% endblock content %}