ZNU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from ZNU.settings import MEDIA_URL, MEDIA_ROOT, DEBUG


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls', namespace="main_page")),
    path('users/', include('users.urls', namespace="users")),
    path('zayavki/', include('zayavki.urls', namespace="zayavki")),
    # path('comments/', include('comments.urls', namespace="comments")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main_page/urls.py
from django.urls import path
from .views import index

app_name = "main_page"
urlpatterns = [
    path("", index, name="index")]

users/urls.py
from django.urls import path
from .views import login, profile, register, logout

app_name = "users"
urlpatterns = [
    path("login", login, name="login"),
    path("profile", profile, name="profile"),
    path("register", register, name="register"),
    path("logout", logout, name="logout")
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# from zayavki.models import FiltersOfZayavok

# Create your models here.



class Shops(models.Model):
    nameshop = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = "Магазины"
        verbose_name = "Магазин"

    def __str__(self):
        return self.nameshop    

class Category(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = "Категории"
        verbose_name = "Категория"

    def __str__(self):
        return self.name

class Roles(models.Model):
    namerole = models.CharField(max_length=30)
    work_category = models.ManyToManyField(Category, default=None, blank=True) 
    # default_filter = models.ForeignKey(FiltersOfZayavok, on_delete=models.PROTECT, null=True, default=None, blank=True) 
    class Meta:
        verbose_name_plural = "Роли"
        verbose_name = "Роль"

    def __str__(self):
        return self.namerole

class User(AbstractUser):
    email = models.EmailField(blank=True)
    role = models.ForeignKey(Roles, on_delete=models.PROTECT, null=True, default=None) 
    shop = models.ForeignKey(Shops, on_delete=models.PROTECT, null=True, default=None, blank=True)
           

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.forms import fields

from users.models import User

class UserLoginForm(AuthenticationForm):
    name_class = 'form-control py-4'
    attrs_username = {"class" : name_class,
                    'placeholder' : "Введите имя пользователя"}
    attrs_password = {"class" : name_class,
                    'placeholder' : "Введите пароль"}
    username = forms.CharField(widget=forms.TextInput(attrs=attrs_username))
    password = forms.CharField(widget=forms.PasswordInput(attrs=attrs_password))
    class Meta:
        model = User
        fields = ("username", "password")

class UserRegistrationForm (UserCreationForm):
    name_class = "form-control py-4"
    attrs_for_username = {"class" : name_class,
                    'placeholder' : "Введите имя пользователя"}
    attrs_for_email = {"class" : name_class,
                    'placeholder' : "Введите адрес эл. почты"}
    attrs_for_password1 = {"class" : name_class,
                    'placeholder' : "Введите пароль"}
    attrs_for_password2 = {"class" : name_class,
                    'placeholder' : "Подтвердите пароль"}

    username = forms.CharField(widget=forms.TextInput(attrs=attrs_for_username))
    email = forms.CharField(widget=forms.EmailInput(attrs=attrs_for_email))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_for_password1))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_for_password2))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

class UserProfileForm(UserChangeForm):
    name_class = "form-control py-4"
    attrs_for_email = {"class" : name_class}
    email = forms.CharField(widget=forms.EmailInput(attrs=attrs_for_email))
        
    class Meta:
        model = User
        fields = ("email",)

users/views.py
from django.http.request import HttpHeaders
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth.decorators import login_required

from users.forms import UserLoginForm
from users.forms import UserRegistrationForm
from users.forms import UserProfileForm
# Create your views here.


def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active and user.role:                
                auth.login(request, user)
                return HttpResponseRedirect(reverse("main_page:index"))
            else: 
                pass     
                # TODO переадресовать на шаблон с сообщением о невозможности авторизации с указанием причин          
                
    else:
        form = UserLoginForm()
    template = "users/login.html"
    context = {"form": form}
    return render(request, template, context)


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))
        else:
            print(form.errors)
    else:
        form = UserRegistrationForm
    template = "users/register.html"
    context = {"form": form}
    return render(request, template, context)


@login_required
def profile(request):
    if request.method=="POST":
        form = UserProfileForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            print(form)
            form.save()
        return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)
        print(request.user.shop)
    template = "users/profile.html"
    context = {"form": form}
    # import pdb; pdb.set_trace()
    return render(request, template, context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("main_page:index"))    

users/templates/users/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Авторизация</title>
    <link href= {% static '/css/auth.css' %} rel="stylesheet"/>
    {% comment %} <link href= {% static '/vendor/bootstrap/css/bootstrap.min.css' %}  rel="stylesheet"> {% endcomment %}
    <link href= {% static '/css/profile.css' %} rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-light" style="max-width: 750px; margin: auto;">
<div id="layoutAuthentication">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'main_page:index' %}">Gamepark Office</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    {% comment %} <li class="nav-item">
                        <a class="nav-link" href="../products.html">Каталог <i class="fas fa-shopping-bag"></i></a>
                    </li> {% endcomment %}
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'users:profile' %}">{{user.username }} <i class="fas fa-user-circle"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                        </li>
                    {% endif %}

                    
                </ul>
            </div>
        </div>
    </nav>
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src= {% static '/js/auth.js' %} ></script>
</body>
</html>

users/templates/users/login.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}    
    <link href= {% static '/css/auth.css' %} rel="stylesheet"/>
    <link href= {% static 'styles.css' %} rel="stylesheet">
{% endblock css %}


{% block content %}
<div class="col-lg-5 container">
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                style="margin-top: 50px;">
            {{form.non_field_errors}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
        </div>
        <div class="card-body">
            <form action= "{% url 'users:login' %}" method="post">
                {% csrf_token %}
                
                <div class="form-group">
                    <label class="small mb-1" for={{ form.username.id_for_label }}>Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    <label class="small mb-1" for={{ form.password.id_for_label }}>Пароль</label>
                    {{ form.password }}
                </div>
                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                    <a class="small" href="#">Забыли пароль?</a>
                    <input class="btn btn-primary" type="submit" value="Авторизоваться">
                </div>
            </form>
        </div>
        <div class="card-footer text-center">
            <div class="small"><a href={% url 'users:register' %}>Нужен аккаунт? Зарегистрируйся!</a></div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'main_page/base.html' %}
{% load  static %}

{% block css %}
    <link href= {% static 'styles.css' %} rel="stylesheet">
{% endblock css %}

{% block content %}
<div class="row">
        <div class="col-lg-12">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %} 
                                
                <div class="form-row">
                    <div class="col-lg-12">
                        <p class="mb-1">Имя пользователя: {{user.username}}</p>                        
                    </div>
                    <div class="col-lg-12">
                        <p class="mb-1">Магазин: {{user.shop}} </p>                        
                    </div>
                    <div class="col-lg-12">
                        <p class="mb-1">Роль: {{user.role}} </p>                        
                    </div>
                    <div class="col-lg-12">
                        <label class="mb-1" for={{form.email.id_for_input}}>Адрес электронной
                            почты:</label>
                        {{form.email}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>

    </div>
{% endblock content %}

users/templates/users/register.html
{% extends 'main_page/base.html' %}
{% load static %}

{% block css %}
    <link href= {% static 'styles.css' %} rel="stylesheet">
    <link href= {% static '/css/auth.css' %}  rel="stylesheet"/>
{% endblock css %}

{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Регистрация</title>
    <link href= {% static '/css/auth.css' %}  rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary"> {% endcomment %}

{% block content %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        {% if form.errors %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                                style="margin-top: 50px;">
                                {{form.errors}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}    
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action={% url 'users:register' %} method="post">
                                    {% csrf_token %}
                                    
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for={{ form.username.id_for_label}}>Имя пользователя</label>
                                            {{ form.username}}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for={{ form.email.id_for_label}}>Адрес электронной
                                                почты</label>
                                            {{ form.email}}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{ form.password1.id_for_label}}>Пароль</label>
                                                {{ form.password1}}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{ form.password2.id_for_label}}>Подтверждение
                                                    пароля</label>
                                                {{ form.password2}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href={% url 'users:login' %}>Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock content %}
{% comment %} <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src= {% static '/js/auth.js' %} ></script>
</body>
</html> {% endcomment %}